### ISSUE TITLE
Error in Apix\Exception

### ISSUE THREAD

**Issue by jspalink** [frqnck/apix#5]
The parameters for Apix\Exception::errorHandler are incorrect.  The final parameter `$ctx` should be `\Exception $e`, the previous Exception that is passed along with it.  As it currently stands, the following error is passed, and can be replicated with the following code:

```php
php > throw new ErrorException("an oops occurred", 400, 0, 'somefile', 10, array());
```
```
PHP Fatal error:  Wrong parameters for ErrorException([string $exception [, long $code, [ long $severity, [ string $filename, [ long $lineno  [, Exception $previous = NULL]]]]]]) in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. ErrorException->__construct() php shell code:1

Fatal error: Wrong parameters for ErrorException([string $exception [, long $code, [ long $severity, [ string $filename, [ long $lineno  [, Exception $previous = NULL]]]]]]) in php shell code on line 1

Call Stack:
  336.6461     239752   1. {main}() php shell code:0
  336.6462     240640   2. ErrorException->__construct() php shell code:1
```

An empty array, BTW, is what is getting passed in, but I'm not sure where from - the error code that I'm seeing doesn't give me a clear indication of where it is.  The error code from the API I'm working on looks like this:

```
Fatal error: Wrong parameters for ErrorException([string $exception [, long $code, [ long $severity, [ string $filename, [ long $lineno  [, Exception $previous = NULL]]]]]]) in /home/jspalink/dev/info-econtext-api/vendor/apix/apix/src/php/Apix/Exception.php on line 36

Call Stack:
    0.0001     239728   1. {main}() /home/jspalink/dev/info-econtext-api/public/index.php:0
    0.0070    1011240   2. Apix\Main->run() /home/jspalink/dev/info-econtext-api/public/index.php:12
    0.0260    1241392   3. Apix\Response->generate() /home/jspalink/dev/info-econtext-api/vendor/apix/apix/src/php/Apix/Main.php:201
    0.0260    1242144   4. Apix\Exception::errorHandler() /home/jspalink/dev/info-econtext-api/vendor/apix/apix/src/php/Apix/Main.php:391
    0.0261    1249280   5. ErrorException->__construct() /home/jspalink/dev/info-econtext-api/vendor/apix/apix/src/php/Apix/Exception.php:36


<h1>500 Internal Server Error</h1>#1 Shutdown:- Wrong parameters for ErrorException([string $exception [, long $code, [ long $severity, [ string $filename, [ long $lineno  [, Exception $previous = NULL]]]]]]) @ /home/jspalink/dev/info-econtext-api/vendor/apix/apix/src/php/Apix/Exception.php:36
```

Obviously, there is no `/apix/apix/src/php/Apix/Main.php:391`

**Comment by jspalink** [comment]
The call to \ErrorException here is still problematic.  `$ctx` should be removed from that call.  Please see the constructor documentation for \ErrorException: http://php.net/manual/en/errorexception.construct.php

**Comment by frqnck** [comment]
Humm...

`Apix\Exception::errorHandler` is set by a standard PHP `set_error_handler` function which HAS for fifth parameter a context array -- this must be the reason for that empty array() being passed thru....

> errcontext
> The fifth parameter is optional, errcontext, which is an array that points to the active symbol table at the point the error occurred. In other words, errcontext will contain an array of every variable that existed in the scope the error was triggered in. User error handler must not modify error context.

See: http://php.net/manual/en/function.set-error-handler.php

**Comment by jspalink** [comment]
Right, the error handler is set correctly, but the instantiation of
errorexception does not use the context variable; it accepts a previous
exception.

**Comment by frqnck** [comment]
`set_error_handler` does return a context array here which is more likely the issue you are encountering.

I agree semantically tho `$ctx` is a poor name for the last param indeed in `Apix\Exception::errorHandler` more especially in context of PHP 5.3. That param was probably added before the `$previous` param ever made it to PHP 5.3.

So let's rename it to `$previous` and somehow type hint it to \Exception -- maybe as follow:

```php
    /**
     *  E_RECOVERABLE_ERROR handler.
     *
     *  Use to re-throw E_RECOVERABLE_ERROR as they occur.
     *
     * @param  int             $code     The error number.
     * @param  string          $msg      The error message.
     * @param  string          $file     The filename where the error occured.
     * @param  int             $line     The line number where it happened.
     * @param  \Exception|null $previous The previous chaining Exception.
     * @throws \ErrorException
     */
    public static function errorHandler(
        $code, $msg='', $file=__FILE__, $line=__LINE__, $previous=null
    ) {
        if (E_RECOVERABLE_ERROR == $code) {
            $msg = preg_replace('@to\s.*::\w+\(\)@', '', $msg, 1);
            // $code = 400; // Due to a client error, recoverable.
        }
        $code = 500; // Set as a HTTP Internal Server Error.

        if ( null !== $previous && !($previous instanceof \Exception) ) {
            $previous = null;
        }

        throw new \ErrorException($msg, $code, 0, $file, $line, $previous);
    }
```

Coud you try this in your current context.
